#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_DIR="$(cd $SCRIPT_DIR/.. && pwd)"

docker rm -f "pshardcompile"
if [[ $(uname) == 'Linux' ]]; then
    UID_PARAMS="-e HOSTUSER=$USER -e HOSTUID=$(id -u)"
fi

docker run -v ~/shards:/shards -p 5434:5432 $UID_PARAMS -v $REPO_DIR:/code -t -i --name "pshardcompile" "pshardcompile" 
